#!/usr/local/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Fbsouzas\StringCalculator\Commands\CalculateStringCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new CalculateStringCommand());

$application->run();
