version: "3.7"
services:
  string-calculator-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: string-calculator-app
    container_name: string-calculator-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    command: php -S 0.0.0.0:9000
